# Generated by Django 3.2.2 on 2021-05-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storie',
            old_name='name',
            new_name='title',
        ),
    ]
